<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Permission_Role extends Model
{
    protected $table = "permission_role";

     protected $fillable = [
        'name',
        'centerid',
        'addObservation',
        'approveObservation',
        'deleteObservation',
        'updateObservation',
        'viewAllObservation',
        'addReflection',
        'approveReflection',
        'updateReflection',
        'deleteReflection',
        'viewAllReflection',
        'addQip',
        'editQip',
        'deleteQip',
        'downloadQip',
        'printQip',
        'mailQip',
        'viewQip',
        'viewRoom',
        'addRoom',
        'editRoom',
        'deleteRoom',
        'addProgramPlan',
        'editProgramPlan',
        'viewProgramPlan',
        'deleteProgramPlan',
        'addAnnouncement',
        'approveAnnouncement',
        'deleteAnnouncement',
        'updateAnnouncement',
        'viewAllAnnouncement',
        'addSurvey',
        'approveSurvey',
        'deleteSurvey',
        'updateSurvey',
        'viewAllSurvey',
        'addRecipe',
        'approveRecipe',
        'deleteRecipe',
        'updateRecipe',
        'addMenu',
        'approveMenu',
        'deleteMenu',
        'updateMenu',
        'viewDailyDiary',
        'updateDailyDiary',
        'updateHeadChecksDaily',
        'updateAccidents',
        'updateModules',
        'addUsers',
        'viewUsers',
        'deleteSnapshots',
        'editSnapshots',
        'viewSnapshots',
        'updateUsers',
        'addCenters',
        'viewCenters',
        'updateCenters',
        'addParent',
        'viewParent',
        'updateParent',
        'addChildGroup',
        'viewChildGroup',
        'updateChildGroup',
        'updatePermission',
        'addProgress',
        'editProgress',
        'viewProgress',
        'editLesson',
        'viewLesson',
        'printPdfLesson',
        'assessment',
        'addSelfAssessment',
        'editSelfAssessment',
        'deleteSelfAssessment',
        'viewSelfAssessment',
        'addActivity',
        'deleteActivity',
        'editActivity',
        'addsubActivity',
        'deletesubActivity',
        'editsubActivity',
        'created_by',
        'created_at', 
        'updated_at'
    ];

}
