<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PermissionsModel extends Model
{
    protected $table = "permissions";
    public $timestamps = false;
    protected $fillable = [
        'userid',
        'centerid',
        'addObservation',
        'approveObservation',
        'deleteObservation',
        'updateObservation',
        'viewAllObservation',
        'addReflection',
        'approveReflection',
        'updateReflection',
        'deleteReflection',
        'viewAllReflection',
        'addQIP',
        'editQIP',
        'deleteQIP',
        'downloadQIP',
        'printQIP',
        'mailQIP',
        'viewQip',
        'viewRoom',
        'addRoom',
        'editRoom',
        'deleteRoom',
        'addProgramPlan',
        'editProgramPlan',
        'viewProgramPlan',
        'deleteProgramPlan',
        'addAnnouncement',
        'approveAnnouncement',
        'deleteAnnouncement',
        'updateAnnouncement',
        'viewAllAnnouncement',
        'addSurvey',
        'approveSurvey',
        'deleteSurvey',
        'updateSurvey',
        'viewAllSurvey',
        'addRecipe',
        'approveRecipe',
        'deleteRecipe',
        'updateRecipe',
        'addMenu',
        'approveMenu',
        'deleteMenu',
        'updateMenu',
        'viewDailyDiary',
        'updateDailyDiary',
        'updateHeadChecks',
        'updateAccidents',
        'updateModules',
        'addUsers',
        'viewUsers',
        'updateUsers',
        'addCenters',
        'viewCenters',
        'updateCenters',
        'addParent',
        'viewParent',
        'updateParent',
        'addChildGroup',
        'viewChildGroup',
        'updateChildGroup',
        'updatePermission',
        'addprogress',
        'editprogress',
        'viewprogress',
        'editlesson',
        'viewlesson',
        'printpdflesson',
        'assessment',
        'addSelfAssessment',
        'editSelfAssessment',
        'deleteSelfAssessment',
        'viewSelfAssessment',
    ];
}
